# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту maksim.askhaev@gmail.com (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - maksim.askhaev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always